# Calamares Installer Configuration for Locaxlinux
modules-search: [ local ]

instances:
- id:       bootloader
  module:   bootloader
  config:   bootloader.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - networkcfg
  - displaymanager
  - initramfs
  - bootloader
  - umount
- show:
  - finished

branding: locaxlinux
prompt-at-end: true
